### ISSUE TITLE
Install maskrcnn-benchmark in the siammot env or in a seperate env?

### ISSUE THREAD

**Issue by kl2005ad** [amazon-research/siam-mot#18]
Confused by the install instructions.
If I install everything except maskrcnn-benchmark as the instructions showed, I got the following errors when running the demo on a long video (not sure if it is caused by the lack of maskrcnn-benchmark):

Traceback (most recent call last):
  File "demos/demo.py", line 5, in <module>
    from demos.demo_inference import DemoInference
ModuleNotFoundError: No module named 'demos'

**Comment by kl2005ad** [comment]
Problem solved. Installed maskruc

**Comment by JAYCHOU2020** [comment]
> Problem solved. Installed maskrcnn-benchmark in a separate repo but with the same conda env. Set the PATHONPATH with the project dir.

can this code track mutil classes object?

**Comment by AydinAlptug** [comment]
> Problem solved. Installed maskrcnn-benchmark in a separate repo but with the same conda env. Set the PATHONPATH with the project dir.

Can you please explain in more detail?  

- When you said "maskrcnn-benchmark in a separate repo" do you mean perform the installation steps of maskrcnn-benchmark outside of the siam-mot folder?

- I am using Ubuntu. What I need to do for the "Set the PATHONPATH with the project dir." part?

**Comment by DbrRoxane** [comment]
Hi,

Personnally I have one conda environment called "siammot" with python 3.7, cuda 11.0 and pytorch 1.7.1
I have a directory "whatever_name" which contain the repos apex  cityscapesScripts  cocoapi  maskrcnn-benchmark  siam-mot
I follow exactly all the SIAM-MOT installation until MASKRCNN, then, I adapt what they suggest in their installation page for my installation as follow (with conda siammot activated) from my "whatever_name" folder. 

```
# maskrcnn_benchmark and coco api dependencies
pip install ninja yacs cython matplotlib tqdm opencv-python

export INSTALL_DIR=$PWD

# install pycocotools
cd $INSTALL_DIR
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
python setup.py build_ext install

# install cityscapesScripts
cd $INSTALL_DIR
git clone https://github.com/mcordts/cityscapesScripts.git
cd cityscapesScripts/
python setup.py build_ext install

# install apex
cd $INSTALL_DIR
git clone https://github.com/NVIDIA/apex.git
cd apex
python setup.py install --cuda_ext --cpp_ext

# install PyTorch Detection
cd $INSTALL_DIR
git clone https://github.com/facebookresearch/maskrcnn-benchmark.git
cd maskrcnn-benchmark
cuda_dir="maskrcnn_benchmark/csrc/cuda"
perl -i -pe 's/AT_CHECK/TORCH_CHECK/' $cuda_dir/deform_pool_cuda.cu $cuda_dir/deform_conv_cuda.cu
# You can then run the regular setup command
python setup.py build develop

unset INSTALL_DIR

```

Hope it helps,

**Comment by mondrasovic** [comment]
> Confused by the install instructions.
> If I install everything except maskrcnn-benchmark as the instructions showed, I got the following errors when running the demo on a long video (not sure if it is caused by the lack of maskrcnn-benchmark):
> 
> Traceback (most recent call last):
> File "demos/demo.py", line 5, in
> from demos.demo_inference import DemoInference
> ModuleNotFoundError: No module named 'demos'

The library can be installed in the same environment. I see no reason why it should not be. And considering your problem with `ModuleNotFoundError: No module named 'demos'` error, you do not necessarily have to change the `PYTHONPATH` value. All you need is to run the script as a module from within the project root directory, so for example:

```
python -m demos.demo --demo-video <path> --track-class person_vehicle --output-path <path>
```

The trouble with `ModuleNotFoundError` is not specific to this project. It is related to how Python itself manages the execution of scripts.
